apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: quay.io/dsanchor/quarkus-petclinic
  newName: image-registry.openshift-image-registry.svc.cluster.local:5000/sergiopinoholgado/quarkus-petclinic
  newTag: 2cbbad27b76d38761887c1eb38a5b39c42c9dcb4
